title: Harris Nisar # your name (or website title) here
logo: "/images/headshot2-modified.png?raw=true" # your photo (or logo) here
description:
  <a href="https://www.linkedin.com/in/harris-nisar-1b090415a/">View My LinkedIn Profile</a>
  <a href="./pdf/resume.pdf">Download my Resume</a>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
